; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Do not forget to run before building the project:
; 1. `platformio upgrade` and `platformio pkg update`
; 2. `git submodule update --init --remote --recommend-shallow --recursive --single-branch --progress`

[platformio]
; All `build_src_filter` values below are relative to `src_dir` directory,
; so set it to custom root directory instead of default "<Project>/src".
src_dir = ${PROJECT_DIR}
include_dir = ${PROJECT_DIR}
data_dir = ${PROJECT_DIR}
; Use common build cache directory for all projects to get the most efficient cache utilization
; https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/directory/build_cache_dir.html
; https://docs.platformio.org/en/latest/projectconf/interpolation.html
build_cache_dir = ${sysenv.TEMP}/tmp/platformio/build_cache

; Common build configuration for all projects
[env]
platform = espressif32
framework = arduino
build_flags =
    -Wall
    -Wextra
    ; Set MONITOR_SPEED macro to `monitor_speed = <baud>` value and use it for Serial init, so it is always in sync
    -D MONITOR_SPEED=${this.monitor_speed}


;
; Projects
;

[env:imx5_esp32s3]
extends = esp32s3-usb-cdc
;build_type = debug
build_src_filter =
    +<apps/imx-5/*.c*>
    +<apps/imx-5/**/*.c*>
    +<libs/inertial-sense-sdk/src/ISComm.c>
    +<libs/inertial-sense-sdk/src/data_sets.c>
lib_deps =
build_flags = ${env.build_flags}
              ; Add root dir to include path, so that we can include files from libs/...
              -I ${PROJECT_DIR}
              ; --- inertial-sense-sdk ---
              ; Define 'ARM' to prevent error:
              ;   ./libs/inertial-sense-sdk/src/ISConstants.h:107:6: error:
              ;     #error Unknown platform not supported, be sure to set it up here, defining CPU_IS_LITTLE_ENDIAN and CPU_IS_BIG_ENDIAN
              -D ARM
              ; If only ARM is defined, then ./libs/inertial-sense-sdk/src/ISConstants.h will fail with:
              ;   ./libs/inertial-sense-sdk/src/ISConstants.h:143:14: fatal error: printf.h: No such file or directory
              ; so define ARDUINO_SAMD_ZERO to prevent this error.
              ; If only ARDUINO_SAMD_ZERO would be defined instead of ARM, then PLATFORM_IS_ARM would be set to 0,
              ; which is not correct, as the platform is ARM. This define is only to work around the printf.h error.
              -D ARDUINO_SAMD_ZERO
              ; --- ------------------ ---
              ; Debugging using log_* macros
              -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO

              ; Use only I2C Peripheral, on I2C Controller pins
              -D I2C_PERIPHERAL_ON_CONTROLLER_PORT=1

[env:bno085_esp32s3]
extends = esp32s3-usb-cdc
;build_type = debug
build_src_filter = ; CLion does not properly handle **/*.c* pattern alone, so we need to specify both
    +<apps/bno085/*.c*>
    +<apps/bno085/**/*.c*>
lib_deps =
    git+git@github.com:sparkfun/SparkFun_BNO08x_Arduino_Library.git#v1.0.5
build_flags = ${env.build_flags}


;
; Boards (use with `extends = <board>`)
;

[esp32s3-usb-cdc]
; Tested on m5stack-stamps3 board
board = esp32-s3-devkitc-1
; ESP32S3 is connected directly to the USB-C plug, without USB-to-UART adapter chip - the Serial should be
; using the native USB-CDC peripheral of the ESP32S3 chip (ARDUINO_USB_CDC_ON_BOOT=1), which is off by default.
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
; Requesting to set 1200 baud rate signalizes the ESP USB-CDC peripheral to reboot the chip to bootloader mode.
board_upload.use_1200bps_touch = yes
; If software USB stack would be used, the USB port would re-enumerates after the chip is reset to bootloader mode
; and the following line would need to be uncommented to wait for the port to reappear.
; However, this is not necessary with the native USB-CDC peripheral as it stays configured when booting to bootloader.
;board_upload.wait_for_upload_port = yes
; Disable launching the flasher stub, only talk to ROM bootloader - it is true that some features
; might not be available, but the flasher stub does not use the integrated USB CDC peripheral and
; the communication is lost after the stub is launched.
upload_flags = --no-stub
; The upload_port is not specified here, as it is reliably automatically detected by the upload tool
; by inspecting the USB device descriptor of the connected USB-CDC device.
; The USB protocol (USB CDC) is used for serial communications, so the maximum possible speed
; can be used for the monitor_speed, as there is no actual UART hardware communication involved.
monitor_speed = 4000000
;-[esp32s3-usb-cdc]-
